version: '2'
services:
  mongodb:
    image: 'docker.io/bitnami/mongodb:4.2-debian-10'
    volumes:
      - '/home/parse/data/mongodb_data:/bitnami'
  parse:
    image: 'docker.io/bitnami/parse:4-debian-10'
    ports:
      - '1337:1337'
    volumes:
      - '/home/parse/data/parse_data:/bitnami'
    depends_on:
      - mongodb
  parse-dashboard:
    image: 'docker.io/bitnami/parse-dashboard:2-debian-10'
    ports:
      - '80:4040'
    volumes:
      - '/home/parse/data/parse_dashboard_data:/bitnami'
    depends_on:
      - parse
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
